#![allow(dead_code)]

use alloc::string::String;

pub const SYS_GETCWD: usize = 17;
pub const SYS_DUP: usize = 23;
pub const SYS_DUP3: usize = 24;
pub const SYS_FCNTL: usize = 25;
pub const SYS_IOCTL: usize = 29;
pub const SYS_MKDIRAT: usize = 34;
pub const SYS_UNLINKAT: usize = 35;
pub const SYS_LINKAT: usize = 37;
pub const SYS_UMOUNT2: usize = 39;
pub const SYS_MOUNT: usize = 40;
pub const SYS_STATFS: usize = 43;
pub const SYS_FSTATFS: usize = 44;
pub const SYS_TRUNCATE: usize = 45;
pub const SYS_FTRUNCATE: usize = 46;
pub const SYS_FACCESSAT: usize = 48;
pub const SYS_CHDIR: usize = 49;
pub const SYS_OPENAT: usize = 56;
pub const SYS_CLOSE: usize = 57;
pub const SYS_PIPE2: usize = 59;
pub const SYS_GETDENTS64: usize = 61;
pub const SYS_LSEEK: usize = 62;
pub const SYS_READ: usize = 63;
pub const SYS_WRITE: usize = 64;
pub const SYS_READV: usize = 65;
pub const SYS_WRITEV: usize = 66;
pub const SYS_PREAD64: usize = 67;
pub const SYS_PWRITE64: usize = 68;
pub const SYS_SENDFILE: usize = 71;
pub const SYS_PSELECT6: usize = 72;
pub const SYS_PPOLL: usize = 73;
pub const SYS_READLINKAT: usize = 78;
pub const SYS_FSTATAT: usize = 79;
pub const SYS_FSTAT: usize = 80;
pub const SYS_SYNC: usize = 81;
pub const SYS_FSYNC: usize = 82;
pub const SYS_UTIMENSAT: usize = 88;
pub const SYS_EXIT: usize = 93;
pub const SYS_EXIT_GROUP: usize = 94;
pub const SYS_SET_TID_ADDRESS: usize = 96;
pub const SYS_FUTEX: usize = 98;
pub const SYS_SET_ROBUST_LIST: usize = 99;
pub const SYS_GET_ROBUST_LIST: usize = 100;
pub const SYS_NANOSLEEP: usize = 101;
pub const SYS_GETITIMER: usize = 102;
pub const SYS_SETITIMER: usize = 103;
pub const SYS_CLOCK_GETTIME: usize = 113;
pub const SYS_YIELD: usize = 124;
pub const SYS_SCHED_YIELD: usize = 124;
pub const SYS_KILL: usize = 129;
pub const SYS_TKILL: usize = 130;
pub const SYS_TGKILL: usize = 131;
pub const SYS_SIGACTION: usize = 134;
pub const SYS_SIGPROCMASK: usize = 135;
pub const SYS_SIGTIMEDWAIT: usize = 137;
pub const SYS_SIGRETURN: usize = 139;
pub const SYS_TIMES: usize = 153;
pub const SYS_SETPGID: usize = 154;
pub const SYS_GETPGID: usize = 155;
pub const SYS_UNAME: usize = 160;
pub const SYS_GETRUSAGE: usize = 165;
pub const SYS_GETTIMEOFDAY: usize = 169;
pub const SYS_GETPID: usize = 172;
pub const SYS_GETPPID: usize = 173;
pub const SYS_GETUID: usize = 174;
pub const SYS_GETEUID: usize = 175;
pub const SYS_GETGID: usize = 176;
pub const SYS_GETEGID: usize = 177;
pub const SYS_GETTID: usize = 178;
pub const SYS_SYSINFO: usize = 179;
pub const SYS_SBRK: usize = 213;
pub const SYS_BRK: usize = 214;
pub const SYS_MUNMAP: usize = 215;
pub const SYS_CLONE: usize = 220;
pub const SYS_EXECVE: usize = 221;
pub const SYS_MMAP: usize = 222;
pub const SYS_MPROTECT: usize = 226;
pub const SYS_MSYNC: usize = 227;
pub const SYS_WAIT4: usize = 260;
pub const SYS_PRLIMIT64: usize = 261;
pub const SYS_RENAMEAT2: usize = 276;
<<<<<<< HEAD



pub fn sysnum_to_string(sys_num: usize) -> String {
    match sys_num {
        SYS_IOCTL  => "SYS_IOCTL".into(),
        SYS_GETCWD => "SYS_GETCWD".into(),
        SYS_GETUID => "SYS_GETUID".into(),
        SYS_DUP => "SYS_DUP".into(),
        SYS_DUP3 => "SYS_DUP3".into(),
        SYS_MKDIRAT => "SYS_MKDIRAT".into(),
        SYS_LINKAT => "SYS_LINKAT".into(),
        SYS_UNLINKAT => "SYS_UNLINKAT".into(),
        SYS_UMOUNT2 => "SYS_UMOUNT2".into(),
        SYS_FCNTL => "SYS_FCNTL".into(),
        SYS_MOUNT => "SYS_MOUNT".into(),
        SYS_STATFS => "SYS_STATFS".into(),
        SYS_FSTATFS => "SYS_FSTATFS".into(),
        SYS_TRUNCATE => "SYS_TRUNCATE".into(),
        SYS_FTRUNCATE => "SYS_FTRUNCATE".into(),
        SYS_FACCESSAT => "SYS_FACCESSAT".into(),
        SYS_CHDIR => "SYS_CHDIR".into(),
        SYS_OPENAT => "SYS_OPENAT".into(),
        SYS_CLOSE => "SYS_CLOSE".into(),
        SYS_PIPE2 => "SYS_PIPE2".into(),
        SYS_GETDENTS64 => "SYS_GETDENTS64".into(),
        SYS_LSEEK => "SYS_LSEEK".into(),
        SYS_READ => "SYS_READ".into(),
        SYS_WRITE => "SYS_WRITE".into(),
        SYS_READV => "SYS_READV".into(),
        SYS_WRITEV => "SYS_WRITEV".into(),
        SYS_SENDFILE => "SYS_SENDFILE".into(),
        SYS_PSELECT6 => "SYS_PSELECT6".into(),
        SYS_PPOLL => "SYS_PPOLL".into(),
        SYS_READLINKAT => "SYS_READLINKAT".into(),
        SYS_FSTATAT => "SYS_FSTATAT".into(),
        SYS_FSTAT => "SYS_FSTAT".into(),
        SYS_UTIMENSAT => "SYS_UTIMENSAT".into(),
        SYS_EXIT => "SYS_EXIT".into(),
        SYS_EXIT_GROUP => "SYS_EXIT_GROUP".into(),
        SYS_SET_TID_ADDRESS => "SYS_SET_TID_ADDRESS".into(),
        SYS_FUTEX => "SYS_FUTEX".into(),
        SYS_SET_ROBUST_LIST => "SYS_SET_ROBUST_LIST".into(),
        SYS_GET_ROBUST_LIST => "SYS_GET_ROBUST_LIST".into(),
        SYS_NANOSLEEP => "SYS_NANOSLEEP".into(),
        SYS_GETITIMER => "SYS_GETITIMER".into(),
        SYS_SETITIMER => "SYS_SETITIMER".into(),
        SYS_CLOCK_GETTIME => "SYS_CLOCK_GETTIME".into(),
        SYS_YIELD => "SYS_SCHED_YIELD".into(),
        SYS_GETPID => "SYS_GETPID".into(),
        SYS_GETTID => "SYS_GETTID".into(),
        SYS_GETPPID => "SYS_GETPPID".into(),
        SYS_BRK => "SYS_BRK".into(),
        SYS_MUNMAP => "SYS_MUNMAP".into(),
        SYS_CLONE => "SYS_CLONE".into(),
        SYS_EXECVE => "SYS_EXECVE".into(),
        SYS_MMAP => "SYS_MMAP".into(),
        SYS_MPROTECT => "SYS_MPROTECT".into(),
        SYS_MSYNC => "SYS_MSYNC".into(),
        SYS_WAIT4 => "SYS_WAIT4".into(),
        SYS_PRLIMIT64 => "SYS_PRLIMIT64".into(),
        SYS_RENAMEAT2 => "SYS_RENAMEAT2".into(),
        _ => "UNKNOWN".into(),
    }
}
=======
pub const SYS_GETRANDOM: usize = 278;
>>>>>>> 73599fce51808454c7e446d9fc82074df6e31d3d
