[package]
name = "arch"
version = "0.1.0"
edition = "2024"

[dependencies]


[target.'cfg(target_arch = "riscv64")'.dependencies]
riscv = "0.13.0"
sbi-rt = { version = "0.0.2", features = ["legacy"] }