[package]
name = "task"
version = "0.1.0"
edition = "2024"

[dependencies]
executor = { workspace = true }
mem = { workspace = true }
filesystem = { workspace = true }
trap = { workspace = true }
spin = { workspace = true }